FROM nginx:stable-bookworm

#WORKDIR /var/www

#RUN mkdir -p /var/www
#COPY /bencloud-quasar/dist/spa/ /var/www/
COPY /bencloud-quasar/dist/spa/ /usr/share/nginx/html/
# Nginx config: SPA fallback + avoid caching index.html (prevents stale chunk 404s)
COPY ./docker/bencloudapp/conf.d/default.conf /etc/nginx/conf.d/default.conf

# RUN apt-get -y update \
#    && apt-get -y upgrade \
#    && adduser -D -H -u 1000 -s /bin/bash www-data -G www-data

# COPY ./docker/bencloudapp/sites/default-dev.conf /etc/nginx/sites-available/default.conf
COPY ./docker/bencloudapp/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod 555 /docker-entrypoint.sh
RUN chmod -R 555 /usr/share/nginx/html/

# Attempt to work around defender issue
# RUN sed -i 's/exec "\$@"/nginx -g "daemon off;"/g' docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]

